[template]
keys = [
"ecdemo/upstream",
]
owner = "nginx"
mode = "0644"
src = "ecdemo-nginx.tmpl"
dest = "/etc/nginx/sites-enabled/ecdemo.conf"
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"
